/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmproject;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        homePagePanel.setVisible(true);
        yearlyPanel.setVisible(false);
        calculatePanel.setVisible(false);
        passEventPanel.setVisible(false);
        profilePanel.setVisible(false);
        homePageBtn.setBackground(new Color(191,179,155));
        homePageBtn.setForeground(Color.white);
        passEventBtn.setBackground(new Color(35,58,89));
        passEventBtn.setForeground(new Color(209,217,193));
        profileBtn.setBackground(new Color(35,58,89));
        profileBtn.setForeground(new Color(209,217,193));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconPanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        menuLineOne = new javax.swing.JSeparator();
        menuLineTwo = new javax.swing.JSeparator();
        profileBtn = new javax.swing.JLabel();
        passEventBtn = new javax.swing.JLabel();
        homePageBtn = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        exitIcon = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        userArea = new javax.swing.JTextField();
        userLine = new javax.swing.JSeparator();
        email1 = new javax.swing.JLabel();
        emailArea = new javax.swing.JTextField();
        emailLine = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        passwordArea = new javax.swing.JTextField();
        passwordLine = new javax.swing.JSeparator();
        phoneLabel = new javax.swing.JLabel();
        phoneArea = new javax.swing.JTextField();
        phoneLine = new javax.swing.JSeparator();
        genderLabel = new javax.swing.JLabel();
        genderComboBox1 = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        engineerInfoPanel = new javax.swing.JPanel();
        engineerInfoBackground = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        deleteLabel = new javax.swing.JLabel();
        passEventPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        calculatePanel = new javax.swing.JPanel();
        calculateLabel = new javax.swing.JLabel();
        homePagePanel = new javax.swing.JPanel();
        questionOneLabel = new javax.swing.JLabel();
        questionOneText = new javax.swing.JTextField();
        questionOneLine = new javax.swing.JSeparator();
        questionTwoLabel = new javax.swing.JLabel();
        seasonalBtn = new javax.swing.JRadioButton();
        yearlyBtn = new javax.swing.JRadioButton();
        questionThreeLabel = new javax.swing.JLabel();
        herbBtn = new javax.swing.JRadioButton();
        bushBtn = new javax.swing.JRadioButton();
        treeBtn = new javax.swing.JRadioButton();
        questionFourLabel = new javax.swing.JLabel();
        questionFourText = new javax.swing.JTextField();
        questionFourLine = new javax.swing.JSeparator();
        areaInfoLabel = new javax.swing.JLabel();
        questionFiveLabel = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        calculateBtn = new javax.swing.JButton();
        calculateLabe = new javax.swing.JLabel();
        yearlyPanel = new javax.swing.JPanel();
        yearlyBtn1 = new javax.swing.JRadioButton();
        yearlyBtn2 = new javax.swing.JRadioButton();
        yearlyBtn3 = new javax.swing.JRadioButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPanel.setBackground(new java.awt.Color(35, 58, 89));

        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/woman-icon.png"))); // NOI18N

        javax.swing.GroupLayout iconPanelLayout = new javax.swing.GroupLayout(iconPanel);
        iconPanel.setLayout(iconPanelLayout);
        iconPanelLayout.setHorizontalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        iconPanelLayout.setVerticalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(iconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 120));

        menuLineOne.setBackground(new java.awt.Color(191, 179, 155));
        getContentPane().add(menuLineOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 156, 5));

        menuLineTwo.setBackground(new java.awt.Color(191, 179, 155));
        getContentPane().add(menuLineTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 156, 20));

        profileBtn.setBackground(new java.awt.Color(35, 58, 89));
        profileBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(209, 217, 193));
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileBtn.setText("      Profil");
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setName(""); // NOI18N
        profileBtn.setOpaque(true);
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 156, 50));

        passEventBtn.setBackground(new java.awt.Color(35, 58, 89));
        passEventBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passEventBtn.setForeground(new java.awt.Color(209, 217, 193));
        passEventBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passEventBtn.setText("      Geçmiş");
        passEventBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passEventBtn.setName(""); // NOI18N
        passEventBtn.setOpaque(true);
        passEventBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passEventBtnMouseClicked(evt);
            }
        });
        getContentPane().add(passEventBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 156, 50));

        homePageBtn.setBackground(new java.awt.Color(35, 58, 89));
        homePageBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homePageBtn.setForeground(new java.awt.Color(209, 217, 193));
        homePageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homePageBtn.setText("      Ana Sayfa");
        homePageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePageBtn.setName(""); // NOI18N
        homePageBtn.setOpaque(true);
        homePageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageBtnMouseClicked(evt);
            }
        });
        getContentPane().add(homePageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 156, 50));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(209, 217, 193));
        exitBtn.setText("Çıkış");
        exitBtn.setBorder(null);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 518, -1, 30));

        exitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });
        getContentPane().add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        profilePanel.setBackground(new java.awt.Color(191, 179, 155));
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username");
        profilePanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        userArea.setBackground(new java.awt.Color(191, 179, 155));
        userArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userArea.setForeground(new java.awt.Color(58, 125, 140));
        userArea.setBorder(null);
        userArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userAreaFocusGained(evt);
            }
        });
        profilePanel.add(userArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 230, 40));

        userLine.setForeground(new java.awt.Color(255, 255, 255));
        profilePanel.add(userLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 270, -1));

        email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("Email");
        profilePanel.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        emailArea.setBackground(new java.awt.Color(191, 179, 155));
        emailArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailArea.setForeground(new java.awt.Color(58, 125, 140));
        emailArea.setBorder(null);
        emailArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailAreaFocusGained(evt);
            }
        });
        profilePanel.add(emailArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 230, 40));

        emailLine.setForeground(new java.awt.Color(255, 255, 255));
        profilePanel.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 270, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        profilePanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        passwordArea.setBackground(new java.awt.Color(191, 179, 155));
        passwordArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordArea.setForeground(new java.awt.Color(58, 125, 140));
        passwordArea.setBorder(null);
        passwordArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordAreaFocusGained(evt);
            }
        });
        passwordArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAreaActionPerformed(evt);
            }
        });
        profilePanel.add(passwordArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 230, 40));

        passwordLine.setForeground(new java.awt.Color(255, 255, 255));
        profilePanel.add(passwordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 270, -1));

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone");
        profilePanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        phoneArea.setBackground(new java.awt.Color(191, 179, 155));
        phoneArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneArea.setForeground(new java.awt.Color(58, 125, 140));
        phoneArea.setBorder(null);
        phoneArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneAreaFocusGained(evt);
            }
        });
        profilePanel.add(phoneArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 160, 40));

        phoneLine.setForeground(new java.awt.Color(255, 255, 255));
        profilePanel.add(phoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 160, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender");
        profilePanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        genderComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderComboBox1.setForeground(new java.awt.Color(209, 217, 183));
        genderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Man", "Female" }));
        genderComboBox1.setBorder(null);
        genderComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genderComboBox1.setVerifyInputWhenFocusTarget(false);
        profilePanel.add(genderComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 363, 90, 35));

        saveBtn.setBackground(new java.awt.Color(58, 125, 140));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(58, 125, 140));
        saveBtn.setText("Kaydet");
        saveBtn.setBorder(null);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        profilePanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 140, 40));

        saveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn/whiteBtn.png"))); // NOI18N
        profilePanel.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 140, 40));

        engineerInfoPanel.setBackground(new java.awt.Color(191, 179, 155));

        engineerInfoBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engineerInfoBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilPanel.png.png"))); // NOI18N

        javax.swing.GroupLayout engineerInfoPanelLayout = new javax.swing.GroupLayout(engineerInfoPanel);
        engineerInfoPanel.setLayout(engineerInfoPanelLayout);
        engineerInfoPanelLayout.setHorizontalGroup(
            engineerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(engineerInfoBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        engineerInfoPanelLayout.setVerticalGroup(
            engineerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(engineerInfoBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        profilePanel.add(engineerInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 95, 349, 289));

        deleteBtn.setBackground(new java.awt.Color(58, 125, 140));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hesabı Sil");
        deleteBtn.setBorder(null);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilePanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 615, 140, 40));

        deleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn/redBtn.png"))); // NOI18N
        profilePanel.add(deleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 615, 140, 40));

        getContentPane().add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 850, 680));

        passEventPanel.setBackground(new java.awt.Color(191, 179, 155));
        passEventPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilPanel.png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        passEventPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 349, 289));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilPanel.png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        passEventPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 349, 289));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilPanel.png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        passEventPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 349, 289));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilPanel.png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        passEventPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 349, 289));

        getContentPane().add(passEventPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 42, 809, 676));

        calculatePanel.setBackground(new java.awt.Color(191, 179, 155));
        calculatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculatePanel.png"))); // NOI18N
        calculatePanel.add(calculateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 744, -1));

        getContentPane().add(calculatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 760, 270));

        homePagePanel.setBackground(new java.awt.Color(191, 179, 155));
        homePagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionOneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionOneLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionOneLabel.setText("Toprağınıza ektiğiniz son ürün");
        homePagePanel.add(questionOneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        questionOneText.setBackground(new java.awt.Color(191, 179, 155));
        questionOneText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questionOneText.setForeground(new java.awt.Color(58, 125, 140));
        questionOneText.setBorder(null);
        questionOneText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                questionOneTextFocusGained(evt);
            }
        });
        homePagePanel.add(questionOneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 0, 230, 30));

        questionOneLine.setBackground(new java.awt.Color(58, 125, 140));
        questionOneLine.setForeground(new java.awt.Color(58, 125, 140));
        homePagePanel.add(questionOneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 32, 235, -1));

        questionTwoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionTwoLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionTwoLabel.setText("Ekmek istediğiniz ürün tipi");
        homePagePanel.add(questionTwoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        seasonalBtn.setBackground(new java.awt.Color(255, 255, 255));
        seasonalBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        seasonalBtn.setForeground(new java.awt.Color(58, 125, 140));
        seasonalBtn.setText("Mevsimlik");
        seasonalBtn.setBorder(null);
        seasonalBtn.setContentAreaFilled(false);
        seasonalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePagePanel.add(seasonalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 80, -1, -1));

        yearlyBtn.setBackground(new java.awt.Color(255, 255, 255));
        yearlyBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        yearlyBtn.setForeground(new java.awt.Color(58, 125, 140));
        yearlyBtn.setText("Yıllık");
        yearlyBtn.setBorder(null);
        yearlyBtn.setContentAreaFilled(false);
        yearlyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yearlyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearlyBtnMouseClicked(evt);
            }
        });
        homePagePanel.add(yearlyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 80, -1, -1));

        questionThreeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionThreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionThreeLabel.setText("Tür seçimi");
        homePagePanel.add(questionThreeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        herbBtn.setBackground(new java.awt.Color(255, 255, 255));
        herbBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        herbBtn.setForeground(new java.awt.Color(58, 125, 140));
        herbBtn.setText("Ot");
        herbBtn.setBorder(null);
        herbBtn.setContentAreaFilled(false);
        herbBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePagePanel.add(herbBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 150, -1, -1));

        bushBtn.setBackground(new java.awt.Color(255, 255, 255));
        bushBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bushBtn.setForeground(new java.awt.Color(58, 125, 140));
        bushBtn.setText("Çalı");
        bushBtn.setBorder(null);
        bushBtn.setContentAreaFilled(false);
        bushBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bushBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bushBtnActionPerformed(evt);
            }
        });
        homePagePanel.add(bushBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        treeBtn.setBackground(new java.awt.Color(255, 255, 255));
        treeBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        treeBtn.setForeground(new java.awt.Color(58, 125, 140));
        treeBtn.setText("Ağaç");
        treeBtn.setBorder(null);
        treeBtn.setContentAreaFilled(false);
        treeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        treeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeBtnActionPerformed(evt);
            }
        });
        homePagePanel.add(treeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 150, -1, -1));

        questionFourLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionFourLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionFourLabel.setText("Arsa büyüklüğü");
        homePagePanel.add(questionFourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        questionFourText.setBackground(new java.awt.Color(191, 179, 155));
        questionFourText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questionFourText.setForeground(new java.awt.Color(58, 125, 140));
        questionFourText.setBorder(null);
        questionFourText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                questionFourTextFocusGained(evt);
            }
        });
        homePagePanel.add(questionFourText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 201, 140, 35));

        questionFourLine.setBackground(new java.awt.Color(58, 125, 140));
        questionFourLine.setForeground(new java.awt.Color(58, 125, 140));
        homePagePanel.add(questionFourLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 236, 150, -1));

        areaInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        areaInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        areaInfoLabel.setText("dönüm");
        homePagePanel.add(areaInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 217, -1, 30));

        questionFiveLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionFiveLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionFiveLabel.setText("Konum bilgisi");
        homePagePanel.add(questionFiveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        cityComboBox.setBackground(new java.awt.Color(191, 179, 155));
        cityComboBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cityComboBox.setForeground(new java.awt.Color(58, 125, 140));
        cityComboBox.setMaximumRowCount(82);
        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Şehir", "Adana", "Ankara" }));
        cityComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 179, 155), 2));
        cityComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePagePanel.add(cityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 272, 90, 30));

        calculateBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        calculateBtn.setForeground(new java.awt.Color(58, 125, 140));
        calculateBtn.setText("Hesapla");
        calculateBtn.setBorder(null);
        calculateBtn.setContentAreaFilled(false);
        calculateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        homePagePanel.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 40));

        calculateLabe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculateLabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn/whiteBtn.png"))); // NOI18N
        homePagePanel.add(calculateLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 40));

        yearlyPanel.setBackground(new java.awt.Color(191, 179, 155));

        yearlyBtn1.setBackground(new java.awt.Color(255, 255, 255));
        yearlyBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearlyBtn1.setForeground(new java.awt.Color(58, 125, 140));
        yearlyBtn1.setText("0-5 Yıllık");
        yearlyBtn1.setBorder(null);
        yearlyBtn1.setContentAreaFilled(false);
        yearlyBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        yearlyBtn2.setBackground(new java.awt.Color(255, 255, 255));
        yearlyBtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearlyBtn2.setForeground(new java.awt.Color(58, 125, 140));
        yearlyBtn2.setText("5-10 Yıllık");
        yearlyBtn2.setBorder(null);
        yearlyBtn2.setContentAreaFilled(false);
        yearlyBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        yearlyBtn3.setBackground(new java.awt.Color(255, 255, 255));
        yearlyBtn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearlyBtn3.setForeground(new java.awt.Color(58, 125, 140));
        yearlyBtn3.setText("10+ Yıllık");
        yearlyBtn3.setBorder(null);
        yearlyBtn3.setContentAreaFilled(false);
        yearlyBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout yearlyPanelLayout = new javax.swing.GroupLayout(yearlyPanel);
        yearlyPanel.setLayout(yearlyPanelLayout);
        yearlyPanelLayout.setHorizontalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearlyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearlyBtn1)
                    .addComponent(yearlyBtn2)
                    .addComponent(yearlyBtn3))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        yearlyPanelLayout.setVerticalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearlyPanelLayout.createSequentialGroup()
                .addComponent(yearlyBtn1)
                .addGap(5, 5, 5)
                .addComponent(yearlyBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlyBtn3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        homePagePanel.add(yearlyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 150, 100));

        getContentPane().add(homePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 770, 370));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/app-background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bushBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bushBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bushBtnActionPerformed

    private void treeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeBtnActionPerformed

    private void questionFourTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionFourTextFocusGained
        questionFourText.setText("");
    }//GEN-LAST:event_questionFourTextFocusGained

    private void questionOneTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionOneTextFocusGained
        questionOneText.setText("");
    }//GEN-LAST:event_questionOneTextFocusGained

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
       calculatePanel.setVisible(true);
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void userAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userAreaFocusGained
        userArea.setText("");
    }//GEN-LAST:event_userAreaFocusGained

    private void emailAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAreaFocusGained
        emailArea.setText("");
    }//GEN-LAST:event_emailAreaFocusGained

    private void phoneAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneAreaFocusGained
        phoneArea.setText("");
    }//GEN-LAST:event_phoneAreaFocusGained

    private void passwordAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAreaActionPerformed
        passwordArea.setText("");
    }//GEN-LAST:event_passwordAreaActionPerformed

    private void passwordAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordAreaFocusGained
        passwordArea.setText("");
    }//GEN-LAST:event_passwordAreaFocusGained

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
      login frame = new login();
      frame.setVisible(true);
      this.hide();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        homePagePanel.setVisible(false);
        yearlyPanel.setVisible(false);
        calculatePanel.setVisible(false);
        passEventPanel.setVisible(false);
        profilePanel.setVisible(true);
        profileBtn.setBackground(new Color(191,179,155));
        profileBtn.setForeground(Color.white);
        homePageBtn.setBackground(new Color(35,58,89));
        homePageBtn.setForeground(new Color(209,217,193));
        passEventBtn.setBackground(new Color(35,58,89));
        passEventBtn.setForeground(new Color(209,217,193));
    }//GEN-LAST:event_profileBtnMouseClicked

    private void passEventBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passEventBtnMouseClicked
        homePagePanel.setVisible(false);
        yearlyPanel.setVisible(false);
        calculatePanel.setVisible(false);
        passEventPanel.setVisible(true);
        profilePanel.setVisible(false);
        passEventBtn.setBackground(new Color(191,179,155));
        passEventBtn.setForeground(Color.white);
        homePageBtn.setBackground(new Color(35,58,89));
        homePageBtn.setForeground(new Color(209,217,193));
        profileBtn.setBackground(new Color(35,58,89));
        profileBtn.setForeground(new Color(209,217,193));
    }//GEN-LAST:event_passEventBtnMouseClicked

    private void homePageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageBtnMouseClicked
        homePagePanel.setVisible(true);
        yearlyPanel.setVisible(false);
        calculatePanel.setVisible(false);
        passEventPanel.setVisible(false);
        profilePanel.setVisible(false);
        homePageBtn.setBackground(new Color(191,179,155));
        homePageBtn.setForeground(Color.white);
        passEventBtn.setBackground(new Color(35,58,89));
        passEventBtn.setForeground(new Color(209,217,193));
        profileBtn.setBackground(new Color(35,58,89));
        profileBtn.setForeground(new Color(209,217,193));
        
    }//GEN-LAST:event_homePageBtnMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
      login frame = new login();
      frame.setVisible(true);
      this.hide();
    }//GEN-LAST:event_exitIconMouseClicked

    private void yearlyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearlyBtnMouseClicked
        yearlyPanel.setVisible(true);
    }//GEN-LAST:event_yearlyBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaInfoLabel;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton bushBtn;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel calculateLabe;
    private javax.swing.JLabel calculateLabel;
    private javax.swing.JPanel calculatePanel;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField emailArea;
    private javax.swing.JSeparator emailLine;
    private javax.swing.JLabel engineerInfoBackground;
    private javax.swing.JPanel engineerInfoPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JComboBox<String> genderComboBox1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JRadioButton herbBtn;
    private javax.swing.JLabel homePageBtn;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator menuLineOne;
    private javax.swing.JSeparator menuLineTwo;
    private javax.swing.JLabel passEventBtn;
    private javax.swing.JPanel passEventPanel;
    private javax.swing.JTextField passwordArea;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JSeparator passwordLine;
    private javax.swing.JTextField phoneArea;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JSeparator phoneLine;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel questionFiveLabel;
    private javax.swing.JLabel questionFourLabel;
    private javax.swing.JSeparator questionFourLine;
    private javax.swing.JTextField questionFourText;
    private javax.swing.JLabel questionOneLabel;
    private javax.swing.JSeparator questionOneLine;
    private javax.swing.JTextField questionOneText;
    private javax.swing.JLabel questionThreeLabel;
    private javax.swing.JLabel questionTwoLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JRadioButton seasonalBtn;
    private javax.swing.JRadioButton treeBtn;
    private javax.swing.JLabel user;
    private javax.swing.JTextField userArea;
    private javax.swing.JSeparator userLine;
    private javax.swing.JRadioButton yearlyBtn;
    private javax.swing.JRadioButton yearlyBtn1;
    private javax.swing.JRadioButton yearlyBtn2;
    private javax.swing.JRadioButton yearlyBtn3;
    private javax.swing.JPanel yearlyPanel;
    // End of variables declaration//GEN-END:variables
}
