/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmproject;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author LENOVO
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        signUpPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpPanel = new javax.swing.JPanel();
        signUpTitle = new javax.swing.JLabel();
        registerInfo = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        userArea1 = new javax.swing.JTextField();
        userLine1 = new javax.swing.JSeparator();
        email1 = new javax.swing.JLabel();
        emailArea = new javax.swing.JTextField();
        emailLine = new javax.swing.JSeparator();
        pass1 = new javax.swing.JLabel();
        passArea1 = new javax.swing.JTextField();
        passLine1 = new javax.swing.JSeparator();
        phoneLabel = new javax.swing.JLabel();
        phoneArea = new javax.swing.JTextField();
        phoneLine = new javax.swing.JSeparator();
        genderLabel = new javax.swing.JLabel();
        genderComboBox1 = new javax.swing.JComboBox<>();
        signUpBtn1 = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        loginInfo = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        userArea = new javax.swing.JTextField();
        userLine = new javax.swing.JSeparator();
        pass = new javax.swing.JLabel();
        passArea = new javax.swing.JPasswordField();
        passLine = new javax.swing.JSeparator();
        loginBtn = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        signUpInfo = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpPanel.setBackground(new java.awt.Color(20, 47, 64));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpTitle.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        signUpTitle.setForeground(new java.awt.Color(209, 217, 183));
        signUpTitle.setText("Sign Up");
        signUpPanel.add(signUpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        registerInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registerInfo.setForeground(new java.awt.Color(209, 217, 183));
        registerInfo.setText("Enter your details below to register");
        signUpPanel.add(registerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        user1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setText("Username");
        signUpPanel.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, -1, -1));

        userArea1.setBackground(new java.awt.Color(20, 47, 64));
        userArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userArea1.setForeground(new java.awt.Color(255, 255, 255));
        userArea1.setBorder(null);
        userArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userArea1FocusGained(evt);
            }
        });
        userArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userArea1ActionPerformed(evt);
            }
        });
        signUpPanel.add(userArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, 230, 40));

        userLine1.setForeground(new java.awt.Color(255, 255, 255));
        signUpPanel.add(userLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 270, 20));

        email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("Email");
        signUpPanel.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, -1, -1));

        emailArea.setBackground(new java.awt.Color(20, 47, 64));
        emailArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailArea.setForeground(new java.awt.Color(255, 255, 255));
        emailArea.setBorder(null);
        emailArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailAreaFocusGained(evt);
            }
        });
        emailArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAreaActionPerformed(evt);
            }
        });
        signUpPanel.add(emailArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, 230, 40));

        emailLine.setForeground(new java.awt.Color(255, 255, 255));
        signUpPanel.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, 270, -1));

        pass1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        pass1.setText("Password");
        signUpPanel.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, -1, -1));

        passArea1.setBackground(new java.awt.Color(20, 47, 64));
        passArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passArea1.setForeground(new java.awt.Color(255, 255, 255));
        passArea1.setBorder(null);
        passArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passArea1FocusGained(evt);
            }
        });
        signUpPanel.add(passArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 230, 40));

        passLine1.setForeground(new java.awt.Color(255, 255, 255));
        signUpPanel.add(passLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, 270, -1));

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone");
        signUpPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, -1, -1));

        phoneArea.setBackground(new java.awt.Color(20, 47, 64));
        phoneArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneArea.setForeground(new java.awt.Color(255, 255, 255));
        phoneArea.setBorder(null);
        phoneArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneAreaFocusGained(evt);
            }
        });
        signUpPanel.add(phoneArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 485, 160, 40));

        phoneLine.setForeground(new java.awt.Color(255, 255, 255));
        signUpPanel.add(phoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 525, 170, -1));

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender");
        signUpPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 465, -1, -1));

        genderComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderComboBox1.setForeground(new java.awt.Color(209, 217, 183));
        genderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Man", "Female" }));
        genderComboBox1.setBorder(null);
        genderComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpPanel.add(genderComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 492, 90, 30));

        signUpBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        signUpBtn1.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn1.setText("Sign Up");
        signUpBtn1.setBorder(null);
        signUpBtn1.setContentAreaFilled(false);
        signUpBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtn1ActionPerformed(evt);
            }
        });
        signUpPanel.add(signUpBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 138, 38));

        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn/greenBtn.png"))); // NOI18N
        signUpPanel.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        getContentPane().add(signUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 410, 620));

        loginPanel.setBackground(new java.awt.Color(20, 47, 64));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTitle.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(209, 217, 183));
        LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginTitle.setText("Login");
        loginPanel.add(LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 80));

        loginInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginInfo.setForeground(new java.awt.Color(209, 217, 193));
        loginInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginInfo.setText("Enter your details below to continue");
        loginPanel.add(loginInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 40));

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Username");
        loginPanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        userArea.setBackground(new java.awt.Color(20, 47, 64));
        userArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userArea.setForeground(new java.awt.Color(255, 255, 255));
        userArea.setBorder(null);
        userArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userAreaFocusGained(evt);
            }
        });
        userArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAreaActionPerformed(evt);
            }
        });
        loginPanel.add(userArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 40));
        loginPanel.add(userLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 20));

        pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass.setText("Password");
        loginPanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 20));

        passArea.setBackground(new java.awt.Color(20, 47, 64));
        passArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passArea.setForeground(new java.awt.Color(255, 255, 255));
        passArea.setBorder(null);
        passArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passAreaFocusGained(evt);
            }
        });
        passArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passAreaActionPerformed(evt);
            }
        });
        loginPanel.add(passArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 40));
        loginPanel.add(passLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 20));

        loginBtn.setBackground(new java.awt.Color(209, 217, 183));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorder(null);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 140, 40));

        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn/greenBtn.png"))); // NOI18N
        loginPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 140, 40));

        signUpInfo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        signUpInfo.setForeground(new java.awt.Color(132, 143, 108));
        signUpInfo.setText("Don't have an account?");
        loginPanel.add(signUpInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 455, -1, -1));

        signUpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(132, 143, 108));
        signUpBtn.setText("Sign up here");
        signUpBtn.setBorder(null);
        signUpBtn.setContentAreaFilled(false);
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        loginPanel.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 446, 100, 30));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 370, 550));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAreaActionPerformed

    private void userAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userAreaFocusGained
        userArea.setText("");
    }//GEN-LAST:event_userAreaFocusGained

    private void passAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passAreaFocusGained
        passArea.setText("");
    }//GEN-LAST:event_passAreaFocusGained

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
      homepage frame = new homepage();
      frame.setVisible(true);
      this.hide();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        signUpPanel.setVisible(true);
        loginPanel.setVisible(false);
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void passAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passAreaActionPerformed

    private void userArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userArea1FocusGained
        userArea.setText("");
    }//GEN-LAST:event_userArea1FocusGained

    private void userArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userArea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userArea1ActionPerformed

    private void emailAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAreaFocusGained
        emailArea.setText("");
    }//GEN-LAST:event_emailAreaFocusGained

    private void emailAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAreaActionPerformed

    private void passArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passArea1FocusGained
        passArea.setText("");
    }//GEN-LAST:event_passArea1FocusGained

    private void phoneAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneAreaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneAreaFocusGained

    private void signUpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtn1ActionPerformed
        signUpPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_signUpBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel background;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField emailArea;
    private javax.swing.JSeparator emailLine;
    private javax.swing.JComboBox<String> genderComboBox1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginInfo;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JPasswordField passArea;
    private javax.swing.JTextField passArea1;
    private javax.swing.JSeparator passLine;
    private javax.swing.JSeparator passLine1;
    private javax.swing.JTextField phoneArea;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JSeparator phoneLine;
    private javax.swing.JLabel registerInfo;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JButton signUpBtn1;
    private javax.swing.JLabel signUpInfo;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpTitle;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JTextField userArea;
    private javax.swing.JTextField userArea1;
    private javax.swing.JSeparator userLine;
    private javax.swing.JSeparator userLine1;
    // End of variables declaration//GEN-END:variables
}
